### ISSUE TITLE
Error: Download failed: Failed to get download link

### ISSUE THREAD

**Issue by sqmbutbetter** [afkarxyz/SpotiSongDownloader#1]
even after refreshing the cookie and trying a few times, it always comes up with this error instantly for each song in a playlist

**Comment by afkarxyz** [comment]
The issue has been fixed. Please update to v2.2. Thank you.

**Comment by sqmbutbetter** [comment]
this still happens in the exact same way with the new update

**Comment by afkarxyz** [comment]
The problem is that the cookie has expired. It seems the cookie refresh doesn't really work. I'll try to fix it again.

**Comment by afkarxyz** [comment]
The issue has now been completely fixed. Please update to v2.3.
